// Economy Hub — Unified entry into VE$ Active Work · Passive Work · Spend.
// Existing routes remain deep-linkable; this is the navigation shell.

import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import {
  ArrowLeft, DollarSign, Sparkles, Camera, ScrollText, Hammer,
  Briefcase, Cpu, Building2, Award, Palette, ShoppingBag, ShoppingCart,
  Loader2, Activity, TrendingUp, Bolt, MapPin, ChevronRight, Coins
} from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { pushNavHistory } from '@/components/GameNavigation';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

// Hub definitions — single source of truth so deep-links stay consistent.
const BUCKETS = {
  active: {
    label: 'Active Work',
    blurb: 'Hands-on tasks that pay VE$ for your effort and time.',
    accent: 'amber',
    entries: [
      {
        key: 'field-ops', path: '/field-ops', icon: Camera, title: 'Field Ops',
        subtitle: 'Photo · Voice · Video missions',
        body: 'DoorDash-style real-world capture. Snap storefronts, record voice, film actions. Geo bonus on-site.',
        pillar: 'NEW',
      },
      {
        key: 'bounty-board', path: '/bounty-board', icon: ScrollText, title: 'Bounty Board',
        subtitle: 'Exclusive in-world bounties',
        body: 'Rescue missions, recon, first-discovery experiments. Non-automatable, premium VE$.',
      },
      {
        key: 'marketplace', path: '/marketplace', icon: ShoppingCart, title: 'Task Marketplace',
        subtitle: 'Player-posted gigs (VE$ + USD)',
        body: 'Hybrid VE$ / Stripe paid contracts between players. Post or accept.',
      },
      {
        key: 'tasks', path: '/tasks', icon: Bolt, title: 'Micro-Tasks',
        subtitle: 'Instant VE$ payouts',
        body: '13 task types from tagging to transcription. Quick batches, fast cashflow.',
      },
      {
        key: 'task-workbench', path: '/task-workbench', icon: Hammer, title: 'Task Workbench',
        subtitle: 'Factory worker queue',
        body: 'Structured tasks generated by the Task Factory. Claim, submit, auto-validate.',
      },
      {
        key: 'jobs', path: '/jobs', icon: Briefcase, title: 'Jobs Hub',
        subtitle: 'Career system',
        body: 'Long-term professions with career progression and salaried VE$.',
      },
    ],
  },
  passive: {
    label: 'Passive Work',
    blurb: 'Set it and forget it — your AI, hardware, and structures earn for you.',
    accent: 'cyan',
    entries: [
      {
        key: 'ai-partners', path: '/ai-partners', icon: Sparkles, title: 'AI Partners',
        subtitle: '10 AI programs · trust-scaled',
        body: 'Deploy AI workers — Market Analyst, Quest Runner, Energy Harvester. Trust multiplies yield.',
      },
      {
        key: 'compute', path: '/compute', icon: Cpu, title: 'Compute Marketplace',
        subtitle: 'Rent or own hardware',
        body: 'Cloud tiers from VE$0.05/hr or buy a Pi-to-Rack and collect monthly yield.',
      },
      {
        key: 'store-structures', path: '/store?tab=structures', icon: Building2, title: 'Civilization Yield',
        subtitle: 'Buildings that produce',
        body: 'Farms, Forges, Taverns generate food/tools/morale every day.',
      },
    ],
  },
  spend: {
    label: 'Spend VE$',
    blurb: 'Use what you earned. Cosmetics, boosts, infrastructure.',
    accent: 'fuchsia',
    entries: [
      {
        key: 'boutique', path: '/boutique', icon: ShoppingBag, title: 'VE$ Boutique',
        subtitle: 'Frames · Colors · Titles · Boosts',
        body: '24-item catalog. Forge Surge +50% task rewards, Mind Amplifier 2x XP, prismatic frames.',
      },
      {
        key: 'store', path: '/store', icon: ShoppingCart, title: 'In-App Store',
        subtitle: 'USD · Compute Subscriptions · Structures',
        body: 'Top up VE$ with Stripe, subscribe to compute tiers, buy civilization buildings.',
      },
      {
        key: 'avatar-studio', path: '/avatar-studio', icon: Palette, title: 'Avatar Studio',
        subtitle: '64×64 pixel canvas',
        body: 'Design your identity. Unlock premium palettes from the Boutique.',
      },
      {
        key: 'leaderboard', path: '/leaderboard', icon: Award, title: 'Leaderboard',
        subtitle: 'Top earners',
        body: 'See who climbs the VE$ rankings hourly.',
      },
    ],
  },
};

const ACCENT_BG = {
  amber: 'from-amber-500/10 via-orange-500/5 to-transparent border-amber-500/30',
  cyan: 'from-cyan-500/10 via-sky-500/5 to-transparent border-cyan-500/30',
  fuchsia: 'from-fuchsia-500/10 via-pink-500/5 to-transparent border-fuchsia-500/30',
};
const ACCENT_TEXT = { amber: 'text-amber-400', cyan: 'text-cyan-400', fuchsia: 'text-fuchsia-400' };
const ACCENT_BORDER = { amber: 'border-amber-500/30', cyan: 'border-cyan-500/30', fuchsia: 'border-fuchsia-500/30' };

const EconomyHub = () => {
  const navigate = useNavigate();
  const userId = localStorage.getItem('userId');

  const [tab, setTab] = useState('active');
  const [wallet, setWallet] = useState({ balance_ve: 0 });
  const [boosts, setBoosts] = useState([]);
  const [fieldStats, setFieldStats] = useState(null);
  const [loading, setLoading] = useState(true);

  const loadAll = useCallback(async () => {
    try {
      const [walletRes, ownedRes, statsRes] = await Promise.all([
        axios.get(`${API}/cosmetics/wallet/${userId}`).catch(() => ({ data: { balance_ve: 0 } })),
        axios.get(`${API}/cosmetics/owned/${userId}`).catch(() => ({ data: { active_boosts: [] } })),
        axios.get(`${API}/field-ops/stats`).catch(() => ({ data: null })),
      ]);
      setWallet(walletRes.data);
      setBoosts(ownedRes.data?.active_boosts || []);
      setFieldStats(statsRes.data);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => {
    pushNavHistory('/economy');
    if (!userId) { navigate('/auth'); return; }
    loadAll();
  }, [userId, navigate, loadAll]);

  const go = (path) => { pushNavHistory(path); navigate(path); };

  const renderBucket = (bucketKey) => {
    const bucket = BUCKETS[bucketKey];
    return (
      <div className="space-y-3">
        <p className="text-sm text-muted-foreground px-1">{bucket.blurb}</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3" data-testid={`economy-bucket-${bucketKey}`}>
          {bucket.entries.map(e => {
            const Icon = e.icon;
            return (
              <Card
                key={e.key}
                onClick={() => go(e.path)}
                className={`bg-gradient-to-br ${ACCENT_BG[bucket.accent]} rounded-sm hover:scale-[1.01] hover:bg-surface/70 transition cursor-pointer`}
                data-testid={`economy-entry-${e.key}`}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <div className={`p-2 rounded-sm bg-black/40 ${ACCENT_TEXT[bucket.accent]}`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2 mb-0.5">
                        <h3 className="font-cinzel text-sm leading-tight">{e.title}</h3>
                        {e.pillar && (
                          <Badge className="bg-amber-500 text-black text-[10px] tracking-wider">{e.pillar}</Badge>
                        )}
                      </div>
                      <p className="text-[11px] text-muted-foreground font-mono mb-1.5">{e.subtitle}</p>
                      <p className="text-xs text-foreground/80 leading-relaxed">{e.body}</p>
                    </div>
                    <ChevronRight className="w-4 h-4 text-muted-foreground/40 shrink-0 self-center" />
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-obsidian text-foreground" data-testid="economy-hub-page">
      {/* Header */}
      <header className="sticky top-0 z-30 bg-obsidian/90 backdrop-blur-md border-b border-border/30">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between gap-3">
          <button
            onClick={() => navigate('/select-mode')}
            className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition"
            data-testid="economy-back-btn"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="font-cinzel text-sm hidden sm:inline">Modes</span>
          </button>
          <div className="flex items-center gap-2">
            <Coins className="w-5 h-5 text-emerald-400" />
            <h1 className="font-cinzel text-lg sm:text-xl tracking-wide">Economy</h1>
          </div>
          <div className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-500/10 border border-emerald-500/30 rounded-sm">
            <DollarSign className="w-4 h-4 text-emerald-400" />
            <span className="font-mono text-sm text-emerald-300" data-testid="economy-balance">
              {(wallet.balance_ve || 0).toFixed(2)}
            </span>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-6">
        {/* Snapshot card */}
        <Card className="bg-gradient-to-br from-emerald-500/5 to-cyan-500/5 border-emerald-500/20 rounded-sm mb-5">
          <CardContent className="p-4 sm:p-5">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-5">
              <div data-testid="economy-stat-balance">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Wallet</p>
                <p className="font-cinzel text-xl text-emerald-300">VE${(wallet.balance_ve || 0).toFixed(2)}</p>
              </div>
              <div data-testid="economy-stat-boosts">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Active Boosts</p>
                <p className="font-cinzel text-xl text-fuchsia-300">{boosts.length}</p>
                {boosts.length > 0 && (
                  <p className="text-[10px] text-muted-foreground mt-0.5">
                    {boosts.map(b => `${b.boost_type} ×${b.multiplier}`).join(' · ')}
                  </p>
                )}
              </div>
              <div data-testid="economy-stat-ops">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Field Ops Live</p>
                <p className="font-cinzel text-xl text-amber-300">{fieldStats?.active_ops ?? '—'}</p>
              </div>
              <div data-testid="economy-stat-paid">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Network Paid</p>
                <p className="font-cinzel text-xl text-cyan-300">
                  VE${(fieldStats?.total_paid_ve ?? 0).toFixed(2)}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {loading ? (
          <div className="flex items-center justify-center py-16">
            <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <Tabs value={tab} onValueChange={setTab} className="w-full">
            <TabsList className="bg-surface/60 border border-border/30 rounded-sm grid grid-cols-3 w-full sm:w-auto sm:inline-flex">
              <TabsTrigger value="active" data-testid="economy-tab-active">
                <Activity className="w-4 h-4 mr-1.5" /> Active Work
              </TabsTrigger>
              <TabsTrigger value="passive" data-testid="economy-tab-passive">
                <TrendingUp className="w-4 h-4 mr-1.5" /> Passive
              </TabsTrigger>
              <TabsTrigger value="spend" data-testid="economy-tab-spend">
                <ShoppingBag className="w-4 h-4 mr-1.5" /> Spend
              </TabsTrigger>
            </TabsList>
            <TabsContent value="active" className="mt-5">{renderBucket('active')}</TabsContent>
            <TabsContent value="passive" className="mt-5">{renderBucket('passive')}</TabsContent>
            <TabsContent value="spend" className="mt-5">{renderBucket('spend')}</TabsContent>
          </Tabs>
        )}
      </main>
    </div>
  );
};

export default EconomyHub;
